all: morphologischer-kasten.pdf

morphologischer-kasten.pdf: morphologischer-kasten.tex
	xelatex morphologischer-kasten.tex && xelatex morphologischer-kasten.tex

clean:
	rm -f *.aux *.log *.out *.toc
