FLAGS=-V title='ITIL: Kapitel 1 und 2' -V author='Lukas Arnold, Patrick Bucher' -V papersize=a4 -V documentclass=scrartcl -V fontfamily=ebgaramond,helvet -V lang=de

all:
	pandoc -N -S $(FLAGS) *.md -o arnold-bucher_kapitel-1-2.pdf
